app = "hollywood-weekly-platform"
primary_region = "lax"  # Los Angeles - you can change this as needed

[build]
  dockerfile = "Dockerfile"

[env]
  PORT = "8080"
  NODE_ENV = "production"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 1
  processes = ["app"]

[http_service.concurrency]
  type = "connections"
  hard_limit = 1000
  soft_limit = 500

[deploy]
  release_command = "npm run db:push"

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 1024